name: Tests
on:
  push:
    branches: # avoid duplicate workflows on tag
      - '**'

jobs:
  tests:
    runs-on: ubuntu-20.04
    container: node:20
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: /github/home/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          YARN_CACHE_FOLDER: /github/home/.cache/yarn
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
      - name: Export coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/coverage-final.json
